<a href="https://colab.research.google.com/github/jveyccan/learning/blob/main/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from sklearn import datasets

from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier

import pandas as pd
import numpy as np

iris = datasets.load_iris()
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [4]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [5]:
X = iris['data']
Y = iris['target']


In [6]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,train_size = 0.8)


In [9]:
log_clf = LogisticRegression(max_iter=1000)
log_clf.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [11]:
log_pred = log_clf.predict(X_test)
log_pred

array([0, 0, 2, 0, 2, 1, 0, 0, 2, 1, 0, 1, 0, 2, 0, 1, 0, 1, 1, 2, 1, 1,
       1, 0, 1, 2, 1, 2, 2, 1])

In [12]:
Y_test

array([0, 0, 2, 0, 2, 1, 0, 0, 2, 1, 0, 1, 0, 2, 0, 2, 0, 1, 1, 2, 1, 1,
       1, 0, 1, 2, 1, 2, 2, 1])

In [13]:
sgd_clf = SGDClassifier(loss='log')
sgd_clf.fit(X_test, Y_test)


SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='log', max_iter=1000,
              n_iter_no_change=5, n_jobs=None, penalty='l2', power_t=0.5,
              random_state=None, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [14]:
sgd_predict =   sgd_clf.predict(X_test)
sgd_predict

array([0, 0, 2, 0, 2, 0, 0, 0, 2, 2, 0, 2, 0, 2, 0, 2, 0, 0, 2, 2, 0, 2,
       2, 0, 0, 2, 0, 2, 2, 2])

In [18]:
proba = sgd_clf.predict_proba(X_test)
proba

array([[1.00000000e+000, 3.91300996e-211, 3.96701368e-266],
       [1.00000000e+000, 1.25526157e-159, 2.15750881e-250],
       [1.67852712e-074, 5.18194059e-102, 1.00000000e+000],
       [1.00000000e+000, 1.72901045e-143, 4.98776149e-201],
       [2.46241257e-067, 2.62507164e-050, 1.00000000e+000],
       [1.00000000e+000, 4.42323820e-024, 3.69959315e-012],
       [1.00000000e+000, 1.31953095e-177, 4.10378258e-229],
       [1.00000000e+000, 1.25990292e-174, 4.56452527e-230],
       [1.42094443e-105, 8.91285392e-018, 1.00000000e+000],
       [1.22793858e-009, 6.63330488e-023, 9.99999999e-001],
       [1.00000000e+000, 3.67947191e-169, 4.86994326e-229],
       [9.78160698e-027, 8.81018700e-049, 1.00000000e+000],
       [1.00000000e+000, 1.24505416e-134, 3.38495322e-206],
       [8.58714563e-054, 1.07920303e-080, 1.00000000e+000],
       [1.00000000e+000, 1.93438170e-163, 6.36412778e-199],
       [1.18099880e-057, 5.58508079e-061, 1.00000000e+000],
       [1.00000000e+000, 9.64740983e-124

In [19]:
from sklearn.metrics import confusion_matrix

conf_log = confusion_matrix (Y_test, log_pred)
conf_sgd = confusion_matrix(Y_test, sgd_predict)

In [20]:
print("Confusion Matrix of Logistic Model")
conf_log

Confusion Matrix of Logistic Model


array([[10,  0,  0],
       [ 0, 11,  0],
       [ 0,  1,  8]])

In [21]:
print("Confusion Matrix of SGD Model")
conf_sgd

Confusion Matrix of SGD Model


array([[10,  0,  0],
       [ 5,  0,  6],
       [ 0,  0,  9]])

In [22]:
from sklearn.metrics import accuracy_score

accuracy_score(Y_test, log_pred)

0.9666666666666667

In [23]:
accuracy_score(Y_test, sgd_predict)

0.6333333333333333

In [26]:
from sklearn.naive_bayes import CategoricalNB

categoricalNB = CategoricalNB()
categoricalNB.fit(X_train, Y_train)

NB_predict = categoricalNB.predict(X_test)

In [27]:
conf_NB =  confusion_matrix(Y_test, NB_predict)
print("Confusion Matrix of NB Classifier Model")
conf_NB

Confusion Matrix of NB Classifier Model


array([[10,  0,  0],
       [ 0, 11,  0],
       [ 0,  3,  6]])